#!/usr/bin/env python3
"""Erzeugt objects.json (kuratierte Waldbingo-Datenbank) und objects.data.js (Embed)."""
import json
import os
from collections import Counter

# Kürzel für kompakte Definition
ALL_S = ["fruehling", "sommer", "herbst", "winter"]
DAY = ["morgen", "tag"]

def o(id, name, kat, emoji, js, wetter, tz, hab, schwer, kurz, erk, wd, reg=None, gew=1.0):
    return {
        "id": id, "name": name, "kategorie": kat, "emoji": emoji, "iconId": id,
        "jahreszeiten": js, "wetter": wetter, "tageszeit": tz, "habitat": hab,
        "regionen": reg or ["DE-weit"], "schwierigkeit": schwer, "gewicht": gew,
        "info": {"kurz": kurz, "erkennen": erk, "wusstest_du": wd},
    }

OBJ = [
    # ── Tiere ──
    o("eichhoernchen","Eichhörnchen","Tier","🐿️",ALL_S,["klar","bewoelkt"],DAY,
      ["laubwald","mischwald","park"],2,
      "Ein flinkes Nagetier mit buschigem Schwanz, das in Bäumen klettert.",
      "Rotbraunes oder schwarzes Fell, springt von Ast zu Ast.",
      "Es vergräbt Nüsse als Vorrat – und vergisst manche, daraus wachsen neue Bäume!"),
    o("igel","Igel","Tier","🦔",["fruehling","sommer","herbst"],["klar","bewoelkt","nach_regen"],
      ["abend","daemmerung","nacht"],["laubwald","mischwald","park","feldrand"],2,
      "Ein kleines Tier mit Stacheln, das sich bei Gefahr einrollt.",
      "Runde Stachelkugel, schnüffelt am Boden nach Würmern und Käfern.",
      "Im Winter hält der Igel Winterschlaf und wacht erst im Frühling wieder auf."),
    o("reh","Reh","Tier","🦌",ALL_S,["klar","bewoelkt","nebel"],["morgen","daemmerung","abend"],
      ["laubwald","nadelwald","mischwald","lichtung","feldrand"],2,
      "Ein scheues Waldtier mit langen Beinen und großen Ohren.",
      "Braunes Fell, weißer Fleck am Po, springt mit großen Sätzen davon.",
      "Reh-Kitze haben weiße Punkte auf dem Fell – das ist ihre Tarnung im Laub."),
    o("fuchs","Fuchs","Tier","🦊",ALL_S,["klar","bewoelkt"],["daemmerung","abend","nacht"],
      ["laubwald","mischwald","feldrand","lichtung"],3,
      "Ein schlaues Raubtier mit rotem Fell und buschigem Schwanz.",
      "Rotbraun, spitze Schnauze, weiße Schwanzspitze.",
      "Der Fuchs kann Mäuse unter dem Schnee hören und springt dann gezielt hinein."),
    o("maus","Maus","Tier","🐭",ALL_S,["klar","bewoelkt"],DAY+["daemmerung"],
      ["laubwald","mischwald","feldrand","lichtung"],3,
      "Ein winziges Nagetier, das im Laub und Gras huscht.",
      "Klein, graubraun, langer Schwanz, sehr schnell.",
      "Eine Maus kann durch Spalten schlüpfen, die nur so groß wie ein Bleistift sind."),

    # ── Vögel ──
    o("specht","Specht","Vogel","🐦",ALL_S,["klar","bewoelkt"],["morgen","tag"],
      ["laubwald","nadelwald","mischwald"],2,
      "Ein Vogel, der mit dem Schnabel an Baumstämme klopft.",
      "Hört sich an wie schnelles Trommeln am Holz; oft rot am Kopf.",
      "Der Specht klopft bis zu 20-mal pro Sekunde – und bekommt davon keine Kopfschmerzen!"),
    o("amsel","Amsel","Vogel","🐦‍⬛",ALL_S,["klar","bewoelkt","nach_regen"],["morgen","tag","abend"],
      ["laubwald","mischwald","park","feldrand"],1,
      "Ein schwarzer Singvogel mit schönem Gesang.",
      "Männchen tiefschwarz mit gelbem Schnabel, Weibchen braun.",
      "Amseln singen besonders früh am Morgen – manchmal schon vor Sonnenaufgang."),
    o("eule","Eule","Vogel","🦉",ALL_S,["klar","bewoelkt","nebel"],["daemmerung","nacht"],
      ["laubwald","nadelwald","mischwald"],3,
      "Ein nachtaktiver Vogel mit großen runden Augen.",
      "Sitzt still im Baum, ruft „Huhu“, fliegt fast lautlos.",
      "Eulen können ihren Kopf fast ganz herumdrehen, um nach hinten zu schauen."),
    o("vogelnest","Vogelnest","Vogel","🪺",["fruehling","sommer","winter"],["klar","bewoelkt"],DAY,
      ["laubwald","mischwald","park"],2,
      "Ein gebautes Nest aus Zweigen und Gras in einem Baum oder Busch.",
      "Rundes Gebilde aus Halmen und Ästchen, oft gut versteckt.",
      "Im Winter sieht man leere Nester gut, weil keine Blätter mehr im Weg sind."),
    o("feder","Feder","Vogel","🪶",ALL_S,["klar","bewoelkt","wind"],DAY,
      ["laubwald","nadelwald","mischwald","park","feldrand","lichtung"],1,
      "Eine Vogelfeder, die auf den Boden gefallen ist.",
      "Leicht, weich, oft am Boden oder im Gebüsch.",
      "Federn sind hohl – deshalb können Vögel trotz Federkleid ganz leicht fliegen."),

    # ── Insekten / Kleintiere ──
    o("ameise","Ameise","Insekt","🐜",["fruehling","sommer","herbst"],["klar","bewoelkt"],DAY,
      ["laubwald","nadelwald","mischwald","lichtung","feldrand"],1,
      "Ein winziges, fleißiges Insekt, das in großen Völkern lebt.",
      "Schwarz oder rot, läuft in langen Reihen über den Boden.",
      "Eine Ameise kann das Vielfache ihres eigenen Gewichts tragen."),
    o("ameisenhaufen","Ameisenhaufen","Spur","🏔️",ALL_S,["klar","bewoelkt"],DAY,
      ["nadelwald","mischwald","lichtung"],2,
      "Ein großer Hügel aus Nadeln und Erde – das Zuhause der Waldameisen.",
      "Kegelförmiger Haufen, oft an einem Baumstumpf, voller Bewegung.",
      "In einem großen Haufen können über eine Million Ameisen wohnen!"),
    o("biene","Biene","Insekt","🐝",["fruehling","sommer"],["klar","bewoelkt"],DAY,
      ["lichtung","feldrand","park"],1,
      "Ein Insekt, das von Blüte zu Blüte fliegt und Honig macht.",
      "Gelb-schwarz gestreift, summt, sitzt auf Blüten.",
      "Bienen tanzen, um anderen Bienen zu zeigen, wo es die besten Blüten gibt."),
    o("schmetterling","Schmetterling","Insekt","🦋",["fruehling","sommer"],["klar"],DAY,
      ["lichtung","feldrand","park"],1,
      "Ein bunter Falter mit großen Flügeln, der über Blumen flattert.",
      "Zwei bunte Flügelpaare, flattert langsam von Blüte zu Blüte.",
      "Manche Schmetterlinge schmecken mit ihren Füßen, ob eine Blüte lecker ist."),
    o("marienkaefer","Marienkäfer","Insekt","🐞",["fruehling","sommer","herbst"],["klar","bewoelkt"],DAY,
      ["lichtung","feldrand","park","laubwald"],1,
      "Ein kleiner roter Käfer mit schwarzen Punkten.",
      "Halbrund, knallrot mit Punkten, krabbelt auf Blättern.",
      "Die Punkte verraten nicht das Alter – verschiedene Arten haben verschieden viele."),
    o("kaefer","Käfer","Insekt","🪲",["fruehling","sommer","herbst"],["klar","bewoelkt","nach_regen"],DAY,
      ["laubwald","nadelwald","mischwald","lichtung","feldrand"],1,
      "Ein Insekt mit harten Flügeldecken, das am Boden krabbelt.",
      "Glänzender Panzer, sechs Beine, oft unter Steinen oder Holz.",
      "Es gibt mehr Käferarten als jede andere Tiergruppe – mehrere Hunderttausend!"),
    o("spinnennetz","Spinnennetz","Spur","🕸️",["sommer","herbst"],["klar","nebel","nach_regen"],
      ["morgen","tag"],["laubwald","mischwald","lichtung","feldrand"],2,
      "Ein feines, klebriges Netz, das eine Spinne gebaut hat.",
      "Glitzert besonders im Morgentau oder Nebel zwischen Zweigen.",
      "Spinnenseide ist für ihr Gewicht stärker als Stahl."),
    o("schnecke","Schnecke","Tier","🐌",["fruehling","sommer","herbst"],["regen","nach_regen","bewoelkt","nebel"],
      DAY,["laubwald","mischwald","lichtung","feldrand","park"],1,
      "Ein langsames Tier mit oder ohne Haus auf dem Rücken.",
      "Schleimspur am Boden, zwei Fühler mit Augen an den Spitzen.",
      "Schnecken haben tausende winzige Zähnchen auf ihrer Zunge.", None, 1.0),
    o("regenwurm","Regenwurm","Tier","🪱",ALL_S,["regen","nach_regen"],DAY,
      ["laubwald","mischwald","feldrand","park","lichtung"],1,
      "Ein langer, weicher Wurm, der in der Erde lebt.",
      "Rosa-braun, ringelig, kommt bei Regen an die Oberfläche.",
      "Regenwürmer lockern den Boden und sind echte Helfer für die Pflanzen."),
    o("glühwürmchen","Glühwürmchen","Insekt","✨",["sommer"],["klar"],["daemmerung","nacht"],
      ["laubwald","mischwald","lichtung","feldrand"],3,
      "Ein Käfer, der im Dunkeln leuchtet.",
      "Kleine grünliche Lichtpunkte, die in lauen Sommernächten schweben.",
      "Das Leuchten ist „kaltes Licht“ – es entsteht ganz ohne Wärme.", None, 0.8),

    # ── Pflanzen / Bäume ──
    o("eichel","Eichel","Pflanze","🌰",["herbst","winter"],["klar","bewoelkt","nach_regen"],DAY,
      ["laubwald","mischwald","park"],1,
      "Die Frucht der Eiche mit einem kleinen Hütchen.",
      "Braune, glatte Nuss in einem Becher-Hütchen.",
      "Aus einer einzigen Eichel kann ein riesiger Baum von 40 Metern werden."),
    o("kastanie","Kastanie","Pflanze","🌰",["herbst"],["klar","bewoelkt","nach_regen"],DAY,
      ["laubwald","mischwald","park"],1,
      "Eine glänzend braune Frucht aus einer stacheligen Schale.",
      "Glatt und braun, fällt aus grünen Stachelkugeln auf den Boden.",
      "Mit Kastanien und Streichhölzern kann man tolle Tierfiguren basteln."),
    o("tannenzapfen","Tannenzapfen","Pflanze","🌲",ALL_S,["klar","bewoelkt","schnee","frost"],DAY,
      ["nadelwald","mischwald"],1,
      "Der holzige Zapfen einer Nadelbaum-Art.",
      "Braun, schuppig, liegt unter Tannen und Fichten.",
      "Zapfen öffnen ihre Schuppen bei trockenem Wetter und schließen sie bei Nässe."),
    o("blatt","Blatt","Pflanze","🍃",["fruehling","sommer","herbst"],["klar","bewoelkt","wind"],DAY,
      ["laubwald","mischwald","park","feldrand"],1,
      "Ein Blatt von einem Baum oder Strauch.",
      "Grün im Sommer, bunt im Herbst – jede Baumart hat eine andere Form.",
      "Blätter sind wie kleine Küchen: Sie kochen mit Sonnenlicht das Essen für den Baum."),
    o("buntes_blatt","Buntes Herbstblatt","Pflanze","🍂",["herbst"],["klar","bewoelkt","wind","nach_regen"],DAY,
      ["laubwald","mischwald","park","feldrand"],1,
      "Ein rot, gelb oder orange gefärbtes Blatt im Herbst.",
      "Leuchtende Farben, oft schon am Boden.",
      "Die bunten Farben waren schon immer im Blatt – das Grün verschwindet nur im Herbst.", None, 1.2),
    o("blume","Blume","Pflanze","🌼",["fruehling","sommer"],["klar","bewoelkt"],DAY,
      ["lichtung","feldrand","park"],1,
      "Eine blühende Pflanze mit bunten Blütenblättern.",
      "Farbige Blüte auf einem Stängel, oft am Wegrand.",
      "Viele Blumen schließen abends ihre Blüten und öffnen sie morgens wieder."),
    o("loewenzahn","Löwenzahn","Pflanze","🌻",["fruehling","sommer"],["klar","bewoelkt"],DAY,
      ["lichtung","feldrand","park"],1,
      "Eine gelbe Blume, die später zur Pusteblume wird.",
      "Knallgelbe Blüte oder weiße Kugel aus Schirmchen.",
      "Eine Pusteblume kann hunderte Samen mit dem Wind auf die Reise schicken.", None, 1.1),
    o("farn","Farn","Pflanze","🌿",["fruehling","sommer","herbst"],["bewoelkt","nach_regen","nebel","klar"],DAY,
      ["laubwald","nadelwald","mischwald","gewaesser"],1,
      "Eine Pflanze mit fein gefiederten Blättern, ohne Blüten.",
      "Grüne, gefiederte Wedel, oft im schattigen, feuchten Wald.",
      "Farne gab es schon, als die Dinosaurier lebten – sie sind uralt."),
    o("klee","Klee","Pflanze","🍀",["fruehling","sommer"],["klar","bewoelkt"],DAY,
      ["lichtung","feldrand","park"],1,
      "Eine kleine Pflanze mit meist drei Blättchen.",
      "Drei runde Blättchen an einem Stiel; selten vier.",
      "Ein vierblättriges Kleeblatt zu finden gilt als großes Glück."),
    o("brennnessel","Brennnessel","Pflanze","🌱",["fruehling","sommer","herbst"],["klar","bewoelkt","nach_regen"],DAY,
      ["laubwald","mischwald","feldrand","lichtung","gewaesser"],2,
      "Eine Pflanze, die brennt, wenn man sie anfasst – also Vorsicht!",
      "Gezackte grüne Blätter mit feinen Brennhärchen.",
      "Schmetterlingsraupen lieben Brennnesseln – ohne sie gäbe es weniger Falter."),
    o("moos","Moos","Pflanze","🟢",ALL_S,["bewoelkt","nach_regen","nebel","regen","klar"],DAY,
      ["laubwald","nadelwald","mischwald","gewaesser"],1,
      "Ein weicher, grüner Teppich auf Steinen und Baumstämmen.",
      "Dichtes, samtiges Grün, fühlt sich weich und feucht an.",
      "Moos hat keine Wurzeln – es saugt Wasser direkt über die Blättchen auf."),
    o("gras","Gras","Pflanze","🌾",["fruehling","sommer","herbst"],["klar","bewoelkt","wind"],DAY,
      ["lichtung","feldrand","park"],1,
      "Halme, die fast überall auf Wiesen und Lichtungen wachsen.",
      "Lange grüne Halme, die im Wind schaukeln.",
      "Manche Gräser wachsen schneller, wenn man sie abschneidet – clever!"),
    o("beeren","Beeren","Pflanze","🫐",["sommer","herbst"],["klar","bewoelkt"],DAY,
      ["laubwald","mischwald","lichtung","feldrand"],2,
      "Kleine bunte Früchte an Sträuchern – nur anschauen, nicht essen!",
      "Rote, blaue oder schwarze Kügelchen an Zweigen.",
      "Viele Waldbeeren sind für uns giftig, aber für Vögel ein leckeres Festmahl."),

    # ── Bäume / Holz ──
    o("baumrinde","Baumrinde","Baum","🪵",ALL_S,["klar","bewoelkt","frost","schnee","nach_regen"],DAY,
      ["laubwald","nadelwald","mischwald","park"],1,
      "Die raue Außenhaut eines Baumstamms.",
      "Rissige oder glatte Schicht außen am Stamm, je nach Baumart.",
      "Die Rinde schützt den Baum wie eine Haut vor Kälte, Hitze und Tieren."),
    o("baumstumpf","Baumstumpf","Baum","🪵",ALL_S,["klar","bewoelkt","nach_regen","schnee"],DAY,
      ["laubwald","nadelwald","mischwald","lichtung"],1,
      "Der Rest eines gefällten oder umgestürzten Baumes.",
      "Flacher Holzstrunk am Boden, oft mit Jahresringen.",
      "An den Ringen im Holz kann man ablesen, wie alt der Baum geworden ist."),
    o("tannenzweig","Tannenzweig","Baum","🌲",ALL_S,["klar","bewoelkt","schnee","frost"],DAY,
      ["nadelwald","mischwald"],1,
      "Ein Zweig mit Nadeln von einer Tanne oder Fichte.",
      "Grüne Nadeln statt Blätter, riecht würzig nach Wald.",
      "Nadelbäume bleiben grün, weil ihre Nadeln auch im Winter dranbleiben."),
    o("wurzel","Wurzel","Baum","🌳",ALL_S,["klar","bewoelkt","nach_regen"],DAY,
      ["laubwald","nadelwald","mischwald"],2,
      "Eine Baumwurzel, die aus dem Boden ragt.",
      "Holziger Strang, der über den Weg oder aus dem Hang wächst.",
      "Die Wurzeln eines Baumes sind oft so breit wie seine ganze Krone."),
    o("totholz","Morsches Holz","Baum","🪵",ALL_S,["bewoelkt","nach_regen","nebel"],DAY,
      ["laubwald","nadelwald","mischwald"],2,
      "Ein altes, vermoderndes Stück Holz voller Leben.",
      "Weiches, brüchiges Holz, oft mit Pilzen und Käfern.",
      "Totholz ist gar nicht tot – darin wohnen unzählige Käfer, Pilze und Würmer."),

    # ── Pilze ──
    o("pilz","Pilz","Pilz","🍄",["sommer","herbst"],["nach_regen","bewoelkt","nebel","regen"],DAY,
      ["laubwald","nadelwald","mischwald"],2,
      "Ein Pilz mit Hut und Stiel – nur anschauen, nicht anfassen!",
      "Schirmchen auf einem Stiel, oft nach Regen aus dem Boden.",
      "Der größte Teil eines Pilzes lebt unsichtbar als Fäden im Boden.", None, 1.0),
    o("fliegenpilz","Fliegenpilz","Pilz","🍄",["herbst"],["nach_regen","bewoelkt","nebel"],DAY,
      ["laubwald","nadelwald","mischwald"],1,
      "Ein roter Pilz mit weißen Punkten – giftig, nur anschauen!",
      "Knallroter Hut mit weißen Tupfen.",
      "Der Fliegenpilz ist berühmt aus Märchen, aber für uns giftig.", None, 0.9),
    o("baumpilz","Baumpilz","Pilz","🍄‍🟫",ALL_S,["bewoelkt","nach_regen","nebel","klar"],DAY,
      ["laubwald","nadelwald","mischwald"],2,
      "Ein Pilz, der wie eine Konsole aus einem Baumstamm wächst.",
      "Halbrunde, harte Scheibe seitlich am Stamm.",
      "Manche Baumpilze werden viele Jahre alt und wachsen jedes Jahr ein Stück."),

    # ── Spuren / Funde ──
    o("pfotenabdruck","Tierspur","Spur","🐾",ALL_S,["nach_regen","schnee","frost"],DAY,
      ["laubwald","nadelwald","mischwald","feldrand","lichtung"],3,
      "Ein Fußabdruck eines Tieres in Schlamm oder Schnee.",
      "Abdrücke im weichen Boden – mal mit Krallen, mal mit Hufen.",
      "An der Spur erkennen Förster, welches Tier hier vorbeigekommen ist."),
    o("federn_rupfung","Federn am Boden","Spur","🪶",ALL_S,["klar","bewoelkt","wind"],DAY,
      ["laubwald","mischwald","feldrand","lichtung"],2,
      "Mehrere Federn an einer Stelle – ein Zeichen, dass hier etwas war.",
      "Eine kleine Ansammlung loser Federn am Boden.",
      "Solche Stellen verraten, dass ein Greifvogel oder Fuchs auf Jagd war."),
    o("nussschale","Angeknabberte Nuss","Spur","🌰",["herbst","winter"],["klar","bewoelkt","nach_regen"],DAY,
      ["laubwald","mischwald","park"],2,
      "Eine Nuss- oder Zapfenschale, an der ein Tier geknabbert hat.",
      "Aufgeknackte Schalen oder zernagte Zapfen am Boden.",
      "An den Nagespuren erkennt man, ob ein Eichhörnchen oder eine Maus gefuttert hat."),
    o("schneckenhaus","Leeres Schneckenhaus","Spur","🐚",ALL_S,["klar","bewoelkt","nach_regen"],DAY,
      ["laubwald","mischwald","feldrand","park"],2,
      "Das leere Haus einer Schnecke.",
      "Gewundenes, hohles Häuschen ohne Bewohner.",
      "Das Häuschen wächst mit der Schnecke mit – sie trägt ihr Zuhause immer dabei."),

    # ── Landschaft / Objekte ──
    o("steine","Steine","Landschaft","🪨",ALL_S,["klar","bewoelkt","schnee","frost","nach_regen"],DAY,
      ["laubwald","nadelwald","mischwald","gewaesser","gebirge","lichtung"],1,
      "Ein Stein oder eine Gruppe Steine am Wegrand.",
      "Hart, grau oder bunt, mal glatt, mal kantig.",
      "Unter Steinen verstecken sich oft Käfer, Asseln und kleine Tiere."),
    o("pfuetze","Pfütze","Landschaft","💧",ALL_S,["regen","nach_regen"],DAY,
      ["laubwald","mischwald","feldrand","lichtung"],1,
      "Eine Wasserlache auf dem Weg nach dem Regen.",
      "Spiegelnde Wasserfläche in einer Senke am Boden.",
      "In großen Waldpfützen kann man manchmal Frösche oder Mückenlarven entdecken.", None, 1.0),
    o("bach","Bach","Landschaft","🏞️",ALL_S,["klar","bewoelkt","nach_regen"],DAY,
      ["gewaesser","laubwald","mischwald","gebirge"],2,
      "Ein kleines, fließendes Gewässer im Wald.",
      "Schmales, plätscherndes Wasser über Steine und Kies.",
      "Das Plätschern entsteht, weil das Wasser über Steine springt und Luft mitnimmt."),
    o("bank","Waldbank","Landschaft","🪑",ALL_S,["klar","bewoelkt","schnee","frost"],DAY,
      ["laubwald","nadelwald","mischwald","lichtung","park"],1,
      "Eine Sitzbank zum Ausruhen am Wegrand.",
      "Holzbank, oft an einem schönen Aussichtspunkt.",
      "Viele Waldbänke wurden von Vereinen gespendet – schau mal nach einem Schildchen!"),
    o("aussichtsturm","Aussichtsturm","Landschaft","🗼",ALL_S,["klar","bewoelkt"],DAY,
      ["lichtung","gebirge","mischwald"],3,
      "Ein hoher Turm, von dem man weit über den Wald schauen kann.",
      "Hohes Holz- oder Stahlgerüst mit Treppe und Plattform.",
      "Von oben sieht man, wie ein grüner Teppich – das sind die Baumkronen.", None, 0.7),
    o("wegweiser","Wegweiser","Landschaft","🪧",ALL_S,["klar","bewoelkt","schnee","frost","nebel"],DAY,
      ["laubwald","nadelwald","mischwald","lichtung","gebirge"],1,
      "Ein Schild, das die Richtung und Wege zeigt.",
      "Holz- oder Metallschild mit Pfeilen und Ortsnamen.",
      "Im Wald zeigen farbige Zeichen an Bäumen oft Wanderwege an."),
    o("eiszapfen","Eiszapfen","Landschaft","🧊",["winter"],["frost","schnee"],DAY,
      ["laubwald","nadelwald","mischwald","gebirge","gewaesser"],2,
      "Ein spitzer Zapfen aus Eis, der von etwas herabhängt.",
      "Klares, spitzes Eis an Ästen, Felsen oder Dächern.",
      "Eiszapfen wachsen Tropfen für Tropfen, wenn Schmelzwasser sofort wieder gefriert.", None, 0.9),
    o("raureif","Raureif","Landschaft","❄️",["winter","herbst"],["frost","nebel"],["morgen"],
      ["laubwald","mischwald","feldrand","lichtung","gewaesser"],2,
      "Feine weiße Eiskristalle, die alles wie gezuckert aussehen lassen.",
      "Weißer, glitzernder Belag auf Gräsern und Blättern am Morgen.",
      "Raureif entsteht, wenn Nebeltröpfchen an kalten Pflanzen sofort gefrieren.", None, 0.9),
    o("schneeflocke","Schnee","Landschaft","🌨️",["winter"],["schnee"],DAY,
      ["laubwald","nadelwald","mischwald","lichtung","feldrand","gebirge"],1,
      "Weiße Schneedecke oder fallende Flocken.",
      "Weiß, kalt, bedeckt Boden und Zweige.",
      "Jede Schneeflocke ist sechseckig – und keine gleicht genau der anderen."),
    o("wolke","Wolken","Landschaft","☁️",ALL_S,["bewoelkt","wind","klar"],DAY,
      ["lichtung","feldrand","gebirge","gewaesser"],1,
      "Wolken am Himmel über den Baumkronen.",
      "Weiße oder graue Gebilde am Himmel, die sich langsam bewegen.",
      "Wolken bestehen aus winzigen Wassertröpfchen – zusammen wiegen sie viele Tonnen."),
]

# Validierung
VOK = {
 "kategorie": {"Tier","Vogel","Insekt","Pflanze","Baum","Pilz","Spur","Landschaft"},
 "jahreszeiten": {"fruehling","sommer","herbst","winter"},
 "wetter": {"klar","bewoelkt","regen","nach_regen","schnee","frost","wind","nebel"},
 "tageszeit": {"morgen","tag","abend","daemmerung","nacht"},
 "habitat": {"laubwald","nadelwald","mischwald","gewaesser","lichtung","feldrand","park","gebirge"},
 "regionen": {"DE-weit","nord","sued","gebirge","kueste"},
}
ids = set()
for x in OBJ:
    assert x["id"] not in ids, f"Doppelte id: {x['id']}"
    ids.add(x["id"])
    assert x["kategorie"] in VOK["kategorie"], x
    for k in ("jahreszeiten","wetter","tageszeit","habitat","regionen"):
        for v in x[k]:
            assert v in VOK[k], f"{x['id']}: ungültiger {k}-Wert {v}"
    assert 1 <= x["schwierigkeit"] <= 3
    for f in ("kurz","erkennen","wusstest_du"):
        assert x["info"][f].strip(), f"{x['id']} fehlt info.{f}"

here = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(here,"objects.json"),"w",encoding="utf-8") as f:
    json.dump({"version":1,"count":len(OBJ),"objekte":OBJ}, f, ensure_ascii=False, indent=2)
with open(os.path.join(here,"objects.data.js"),"w",encoding="utf-8") as f:
    f.write("// Auto-generiert von build_data.py – nicht von Hand ändern.\n")
    f.write("window.WB_DATA = ")
    json.dump({"version":1,"count":len(OBJ),"objekte":OBJ}, f, ensure_ascii=False, indent=2)
    f.write(";\n")

# Kategorie-Statistik
cats = Counter(x["kategorie"] for x in OBJ)
print(f"OK: {len(OBJ)} Objekte geschrieben.")
print("Kategorien:", dict(cats))
